"""
tickers.py — curated Nifty 50 + Nifty Next 50 ticker lists for the dropdown.
Format: {"Display name": "SCREENER_TICKER"}
"""

NIFTY_50 = {
    "Adani Enterprises": "ADANIENT",
    "Adani Ports": "ADANIPORTS",
    "Apollo Hospitals": "APOLLOHOSP",
    "Asian Paints": "ASIANPAINT",
    "Axis Bank": "AXISBANK",
    "Bajaj Auto": "BAJAJ-AUTO",
    "Bajaj Finance": "BAJFINANCE",
    "Bajaj Finserv": "BAJAJFINSV",
    "Bharat Electronics": "BEL",
    "Bharat Petroleum": "BPCL",
    "Bharti Airtel": "BHARTIARTL",
    "Britannia Industries": "BRITANNIA",
    "Cipla": "CIPLA",
    "Coal India": "COALINDIA",
    "Dr Reddy's Labs": "DRREDDY",
    "Eicher Motors": "EICHERMOT",
    "Grasim Industries": "GRASIM",
    "HCL Technologies": "HCLTECH",
    "HDFC Bank": "HDFCBANK",
    "HDFC Life Insurance": "HDFCLIFE",
    "Hero MotoCorp": "HEROMOTOCO",
    "Hindalco Industries": "HINDALCO",
    "Hindustan Unilever": "HINDUNILVR",
    "ICICI Bank": "ICICIBANK",
    "IndusInd Bank": "INDUSINDBK",
    "Infosys": "INFY",
    "ITC": "ITC",
    "JSW Steel": "JSWSTEEL",
    "Kotak Mahindra Bank": "KOTAKBANK",
    "Larsen & Toubro": "LT",
    "LTIMindtree": "LTIM",
    "Mahindra & Mahindra": "M&M",
    "Maruti Suzuki": "MARUTI",
    "Nestle India": "NESTLEIND",
    "NTPC": "NTPC",
    "ONGC": "ONGC",
    "Power Grid Corp": "POWERGRID",
    "Reliance Industries": "RELIANCE",
    "SBI Life Insurance": "SBILIFE",
    "Shriram Finance": "SHRIRAMFIN",
    "State Bank of India": "SBIN",
    "Sun Pharmaceutical": "SUNPHARMA",
    "Tata Consultancy Services": "TCS",
    "Tata Consumer Products": "TATACONSUM",
    "Tata Motors": "TATAMOTORS",
    "Tata Steel": "TATASTEEL",
    "Tech Mahindra": "TECHM",
    "Titan Company": "TITAN",
    "Trent": "TRENT",
    "UltraTech Cement": "ULTRACEMCO",
    "Wipro": "WIPRO",
}

NIFTY_NEXT_50 = {
    "ABB India": "ABB",
    "Adani Energy Solutions": "ADANIENSOL",
    "Adani Green Energy": "ADANIGREEN",
    "Adani Power": "ADANIPOWER",
    "Adani Total Gas": "ATGL",
    "Ambuja Cements": "AMBUJACEM",
    "Avenue Supermarts (DMart)": "DMART",
    "Bajaj Holdings": "BAJAJHLDNG",
    "Bank of Baroda": "BANKBARODA",
    "Berger Paints": "BERGEPAINT",
    "Bosch": "BOSCHLTD",
    "Canara Bank": "CANBK",
    "Cholamandalam Investment": "CHOLAFIN",
    "Colgate Palmolive": "COLPAL",
    "DLF": "DLF",
    "Divi's Laboratories": "DIVISLAB",
    "GAIL India": "GAIL",
    "Godrej Consumer": "GODREJCP",
    "Havells India": "HAVELLS",
    "Hindustan Aeronautics": "HAL",
    "ICICI Lombard": "ICICIGI",
    "ICICI Prudential Life": "ICICIPRULI",
    "IndianOil": "IOC",
    "Indian Railway Finance": "IRFC",
    "InterGlobe Aviation (IndiGo)": "INDIGO",
    "Jindal Steel & Power": "JINDALSTEL",
    "LIC Housing Finance": "LICHSGFIN",
    "LIC India": "LICI",
    "Marico": "MARICO",
    "Muthoot Finance": "MUTHOOTFIN",
    "Naukri (Info Edge)": "NAUKRI",
    "PFC": "PFC",
    "PI Industries": "PIIND",
    "Pidilite Industries": "PIDILITIND",
    "Punjab National Bank": "PNB",
    "REC": "RECLTD",
    "Siemens": "SIEMENS",
    "SRF": "SRF",
    "Shree Cement": "SHREECEM",
    "Tata Power": "TATAPOWER",
    "TVS Motor Company": "TVSMOTOR",
    "United Spirits": "MCDOWELL-N",
    "Varun Beverages": "VBL",
    "Vedanta": "VEDL",
    "Vodafone Idea": "IDEA",
    "Zomato": "ZOMATO",
    "Zydus Lifesciences": "ZYDUSLIFE",
}

ALL_TICKERS = {**NIFTY_50, **NIFTY_NEXT_50}
